/*
 * DienstplanService.java
 * generated by rose
 */
package muettinghoven.dienstplan.service;

import retrofit2.http.*;
import java.util.List;
import retrofit2.Call;

public interface DienstplanService
{

	@GET("bewohner")
	public Call<List<muettinghoven.dienstplan.dto.BewohnerDto>> getBewohners();

	@GET("bewohner/{id}")
	public Call<muettinghoven.dienstplan.dto.BewohnerDto> getBewohnerById(@Path("id") final int id);

	@GET("bewohner")
	public Call<List<muettinghoven.dienstplan.dto.BewohnerDto>> getBewohnersByIds(@Query("id") final int[] ids);

	@GET("bewohner/id")
	public Call<List<Integer>> getBewohnerIds();

	@GET("bewohner/count")
	public Call<Integer> getBewohnerCount();

	@POST("bewohner")
	public Call<muettinghoven.dienstplan.dto.BewohnerDto> postBewohner(@Body final muettinghoven.dienstplan.dto.BewohnerDto dto);

	@PUT("bewohner/{id}")
	public Call<Void> putBewohner(@Path("id") final int id, @Body final muettinghoven.dienstplan.dto.BewohnerDto dto);

	@DELETE("bewohner/{id}")
	public Call<Void> deleteBewohnerById(@Path("id") final int id);

	@GET("dienstplan")
	public Call<List<muettinghoven.dienstplan.dto.DienstplanDto>> getDienstplans();

	@GET("dienstplan/{id}")
	public Call<muettinghoven.dienstplan.dto.DienstplanDto> getDienstplanById(@Path("id") final int id);

	@GET("dienstplan")
	public Call<List<muettinghoven.dienstplan.dto.DienstplanDto>> getDienstplansByIds(@Query("id") final int[] ids);

	@GET("dienstplan/id")
	public Call<List<Integer>> getDienstplanIds();

	@GET("dienstplan/count")
	public Call<Integer> getDienstplanCount();

	@POST("dienstplan")
	public Call<muettinghoven.dienstplan.dto.DienstplanDto> postDienstplan(@Body final muettinghoven.dienstplan.dto.DienstplanDto dto);

	@PUT("dienstplan/{id}")
	public Call<Void> putDienstplan(@Path("id") final int id, @Body final muettinghoven.dienstplan.dto.DienstplanDto dto);

	@DELETE("dienstplan/{id}")
	public Call<Void> deleteDienstplanById(@Path("id") final int id);

	@GET("zeitraum")
	public Call<List<muettinghoven.dienstplan.dto.ZeitraumDto>> getZeitraums();

	@GET("zeitraum/{id}")
	public Call<muettinghoven.dienstplan.dto.ZeitraumDto> getZeitraumById(@Path("id") final int id);

	@GET("zeitraum")
	public Call<List<muettinghoven.dienstplan.dto.ZeitraumDto>> getZeitraumsByIds(@Query("id") final int[] ids);

	@GET("zeitraum/id")
	public Call<List<Integer>> getZeitraumIds();

	@GET("zeitraum/count")
	public Call<Integer> getZeitraumCount();

	@POST("zeitraum")
	public Call<muettinghoven.dienstplan.dto.ZeitraumDto> postZeitraum(@Body final muettinghoven.dienstplan.dto.ZeitraumDto dto);

	@PUT("zeitraum/{id}")
	public Call<Void> putZeitraum(@Path("id") final int id, @Body final muettinghoven.dienstplan.dto.ZeitraumDto dto);

	@DELETE("zeitraum/{id}")
	public Call<Void> deleteZeitraumById(@Path("id") final int id);

	@GET("dienst")
	public Call<List<muettinghoven.dienstplan.dto.DienstDto>> getDiensts();

	@GET("dienst/{id}")
	public Call<muettinghoven.dienstplan.dto.DienstDto> getDienstById(@Path("id") final int id);

	@GET("dienst")
	public Call<List<muettinghoven.dienstplan.dto.DienstDto>> getDienstsByIds(@Query("id") final int[] ids);

	@GET("dienst/id")
	public Call<List<Integer>> getDienstIds();

	@GET("dienst/count")
	public Call<Integer> getDienstCount();

	@POST("dienst")
	public Call<muettinghoven.dienstplan.dto.DienstDto> postDienst(@Body final muettinghoven.dienstplan.dto.DienstDto dto);

	@PUT("dienst/{id}")
	public Call<Void> putDienst(@Path("id") final int id, @Body final muettinghoven.dienstplan.dto.DienstDto dto);

	@DELETE("dienst/{id}")
	public Call<Void> deleteDienstById(@Path("id") final int id);

	@GET("dienstausfuehrung")
	public Call<List<muettinghoven.dienstplan.dto.DienstAusfuehrungDto>> getDienstAusfuehrungs();

	@GET("dienstausfuehrung/{id}")
	public Call<muettinghoven.dienstplan.dto.DienstAusfuehrungDto> getDienstAusfuehrungById(@Path("id") final int id);

	@GET("dienstausfuehrung")
	public Call<List<muettinghoven.dienstplan.dto.DienstAusfuehrungDto>> getDienstAusfuehrungsByIds(@Query("id") final int[] ids);

	@GET("dienstausfuehrung/id")
	public Call<List<Integer>> getDienstAusfuehrungIds();

	@GET("dienstausfuehrung/count")
	public Call<Integer> getDienstAusfuehrungCount();

	@POST("dienstausfuehrung")
	public Call<muettinghoven.dienstplan.dto.DienstAusfuehrungDto> postDienstAusfuehrung(@Body final muettinghoven.dienstplan.dto.DienstAusfuehrungDto dto);

	@PUT("dienstausfuehrung/{id}")
	public Call<Void> putDienstAusfuehrung(@Path("id") final int id, @Body final muettinghoven.dienstplan.dto.DienstAusfuehrungDto dto);

	@DELETE("dienstausfuehrung/{id}")
	public Call<Void> deleteDienstAusfuehrungById(@Path("id") final int id);

}
